# 数据为为为配置
server:
  port: 8082
#代码里若想零配置，则yaml文件里面必须这样写；
logging:
  level:
    com:
      looedu:
        mapper: debug
spring:
  datasource:
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: zhtdb
      password: root
      # 下面为接池的种类
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      druid:
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开 PSCache，并且指定每个连接上 PSCache 的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
        filters: stat,slf4j,wall
        # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
        connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
        # 配置 DruidStatFilter
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        # 配置 DruidStatViewServlet
        stat-view-servlet:
          url-pattern: /druid/*
#          # IP 白名单，没有配置或者为空，则允许所有访问
#          allow: 127.0.0.1
#          # IP 黑名单，若白名单也存在，则优先使用
#          deny: 192.168.31.253
          # 禁用 HTML 中 Reset All 按钮
          reset-enable: false
          # 登录用户名/密码
          login-username: root
          login-password: 123
mybatis:
#  check-config-location: true                             # 是否检测MyBatis运行参数配置文件
#  config-location: classpath:/mybatis-config.xml          # 指定MyBatis运行参数配置文件位置
#  mapper-locations: classpath:/mapper/**/*.xml            # 注册XML映射器
#  type-aliases-package: com.example.GrandWorldM.entity             # 配置Java类型包名
#  type-handlers-package: test.springboot.handlers         # 配置类型处理器包名
#  executor-type: SIMPLE                                   # 指定执行器类型
  configuration:
#      default-fetch-size: 20
#      default-statement-timeout: 30
      mapUnderscoreToCamelCase: true #加上驼峰命名的配置，才能将audit_id的值映射到auditId